[package]
name = "barr"
version = "1.8.0"
author = "John Gosset <john@gossetx.com>"
description = "A statusbar generator for dwm(1)"
architecture = "x86_64"
requires = ["wireless_tools", "xorg-xsetroot"]

[[file]]
path = "/usr/bin/barr"
contentFrom = "./barr"
mode = "0755"
owner = "root"
group = "root"

[[file]]
path = "/usr/lib/systemd/user/barr.service"
contentFrom = "./barr.service"
mode = "0644"
owner = "root"
group = "root"
